### ISSUE TITLE
pypi 1.5.1 release contains entry point reference to pylons.test

### ISSUE THREAD

**Issue by Trii** [fixture-py/fixture#19]
The following entry point is configured in `setup.py` in the version pushed to pypi but it is not present in the 1.5.1 release in the master branch.
```
[nose.plugins]
  pylons = pylons.test:PylonsPlugin
```

I don't use pylons and it isn't listed in the package requirements so running nosetests gives me
```
Josh@kapbook:kapx-courses$ ./bin/nosetests
/Users/Josh/Developer/project/eggs/nose-1.3.4-py2.7.egg/nose/plugins/manager.py:395: RuntimeWarning: Unable to load plugin pylons = pylons.test:PylonsPlugin: No module named pylons.test
```

**Comment by LuRsT** [comment]
@Trii Does this problem still persist in the current version?

**Comment by Trii** [comment]
Nope, all cleared!

**Comment by LuRsT** [comment]
Great!
